[config]
game=sf6
chromakey=#000000
stickpos=90,90
stickradius=70

# Specify all action keys in the game (directional keys are handled differently)
[overlay.sf6]
keynames=lp,mp,hp,lk,mk,hk

# Specify graphical assets to be used when rendering the buttons. Remember to put them in the "assets" folder. Use of pure black (#000000) is discouraged.
# Structure: keyname=asset_filename.png,x,y
# NOTE: Sprite assets are anchored around their center, not top-left.
[assets.sf6]
lp=btn_0.png,210,58
mp=btn_1.png,274,58
hp=btn_2.png,338,58
lk=btn_3.png,210,122
mk=btn_4.png,274,122
hk=btn_5.png,338,122

# Bind every key to a corresponding button. Omitted keys will be ignored.
# For possible popular keybinds, see https://github.com/Mihaugoku/fg-input-visualizer
[keyconfig.sf6]
lp=a
mp=s
hp=d
lk=z
mk=x
hk=c

# Combo keys when pressed, will light up all the buttons
# mentioned after the "=", separated by a comma
[combokeys.sf6]
f=mp,mk
v=hp,hk
